version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "io.ktor:ktor-client-core"
      - dependency-name: "io.ktor:ktor-serialization-kotlinx-json"
      - dependency-name: "io.ktor:ktor-client-content-negotiation"
      - dependency-name: "io.ktor:ktor-client-okhttp"
      - dependency-name: "io.ktor:ktor-client-ios"
      - dependency-name: "io.ktor:ktor-client-java"
      - dependency-name: "io.insert-koin:koin-core"
      - dependency-name: "io.insert-koin:koin-compose-viewmodel"
      - dependency-name: "androidx.lifecycle:lifecycle-process"
      - dependency-name: "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose"
      - dependency-name: "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose"
      - dependency-name: "androidx.activity:activity-compose"
      - dependency-name: "org.jetbrains.compose"
      - dependency-name: "app.cash.sqldelight:primitive-adapters"
      - dependency-name: "app.cash.sqldelight:coroutines-extensions"
      - dependency-name: "app.cash.sqldelight:android-driver"
      - dependency-name: "app.cash.sqldelight:native-driver"
      - dependency-name: "app.cash.sqldelight:sqlite-driver"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
