kotlin.code.style=official

#Gradle
org.gradle.jvmargs=-Xmx2048M -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
# Because of this issue: https://stackoverflow.com/a/79606388/4260491
kotlin.native.cacheKind=none
# Disables D8 Kotlin metadata rewriting which crashes on Kotlin 2.3.x + AGP 8.13.x release builds
android.enableR8.fullMode=false

#Kotlin Multiplatform
kotlin.mpp.enableCInteropCommonization=true

#MAVEN CENTRAL
mavenCentralUsername=mavenUsername
mavenCentralPassword=mavenPassword

signing.keyId=gpgKeyId
signing.password=gpgPassword
signing.secretKeyRingFile=gpgSecretKeyLocation

#Ktor libray exchange -> it can be either v3 or v2
inspektify.ktorVersion=v3

#Inspektify enable/disable -> set to false to use the no-op variant in the sample app
inspektify.enabled=true