name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  build:
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run Ktlint
        run: ./gradlew ktlintCheck

      - name: Run Detekt
        run: ./gradlew detekt

      - name: Run konsist tests
        run: ./gradlew :konsistTest:jvmTest

      - name: Build gradle project
        run: ./gradlew assemble
