name: Build

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review, synchronize]
    branches:
      - main

jobs:
  setupMachine:
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Checking out branch
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2.0.10

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - uses: actions/cache@v3
        with:
          path: |
            ./.gradle
          key: gradle-${{ runner.os }}
          restore-keys: |
            gradle-${{ runner.os }}
            gradle-

      - name: kill java processes
        run: |
          wmic process where "name like '%java%'" delete
          taskkill /f /im jqs.exe
          taskkill /f /im javaw.exe
          taskkill /f /im java.exe
        continue-on-error: true

  ktlint:
    needs: setupMachine
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Run Ktlint
        run: ./gradlew ktlintCheck --gradle-user-home .gradle

  detekt:
    needs: setupMachine
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Run Detekt
        run: ./gradlew detekt --gradle-user-home .gradle

  konsist:
    needs: setupMachine
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Run konsist tests
        run: ./gradlew :konsistTest:jvmTest --gradle-user-home .gradle

  buildAndroid:
    needs: setupMachine
    name: Build apps
    runs-on: macos-12

    steps:
      - name: Build gradle project
        run: ./gradlew assemble
